// =============================================================
// SUMBER KEBENARAN TUNGGAL UNTUK RBAC FRONTEND
// Dipakai bersama oleh Sidebar.jsx dan ProtectedRoute.jsx
// =============================================================

// Map: path frontend → permission yang dibutuhkan untuk membukanya
export const ROUTE_PERMISSIONS = {
  "/dashboard":         "dashboard.view",
  "/santri":            "santri.view",
  "/kelas":             "kelas.view",
  "/wali":              "wali.view",
  "/guru":              "guru.view",
  "/absensi":           "absensi.view",
  "/absensi-guru":      "absensi_guru.view",
  "/hafalan":           "hafalan.view",
  "/nilai":             "nilai.view",
  "/pembayaran":        "pembayaran.view",
  "/buku-kas":          "bukukas.view",
  "/kas-instansi":      "kas_instansi.view",
  "/kas-instansi/konsolidasi": "kas_instansi.konsolidasi",
  "/program-unit":      "program_unit.view",
  "/sahriyah":          "sahriyah.view",
  "/sahriyah-setting":  "sahriyah.manage",
  "/pelanggaran":       "pelanggaran.view",
  "/kesehatan":         "kesehatan.view",
  "/perizinan":         "perizinan.view",
  "/tamu":              "tamu.view",
  "/pengumuman":        "pengumuman.view",
  "/wali-home-links":   "pengumuman.view",
  "/profil-pesantren":  "profil.view",
  "/devices":           "device.view",
  "/audit":             "audit.view",
  "/rfid-monitor":      "rfid.view",
  "/rfid-dashboard":    "rfid.view",
  "/rfid-transactions": "rfid.view",
  "/rfid-topup":        "rfid.view",
  "/rfid-merchant":     "rfid.view",
  "/rfid-devices":      "rfid.view",
  "/rfid-mutasi":       "rfid.view",
  "/rfid-refund":       "rfid.view",
  "/users":             "user.view",
  "/roles":             "role.manage",
};

// Map: path frontend → tenant feature key
export const ROUTE_FEATURES = {
  "/dashboard":         "dashboard",
  "/santri":            "santri",
  "/kelas":             "kelas",
  "/wali":              "wali",
  "/guru":              "guru",
  "/absensi":           "pendidikan",
  "/absensi-guru":      "pendidikan",
  "/hafalan":           "pendidikan",
  "/nilai":             "pendidikan",
  "/pembayaran":        "pembayaran",
  "/buku-kas":          "buku_kas",
  "/kas-instansi":      "kas_instansi",
  "/kas-instansi/konsolidasi": "kas_instansi",
  "/program-unit":      "program_unit",
  "/sahriyah":          "sahriyah",
  "/sahriyah-setting":  "sahriyah",
  "/pelanggaran":       "pelanggaran",
  "/kesehatan":         "keamanan",
  "/perizinan":         "perizinan",
  "/tamu":              "keamanan",
  "/pengumuman":        "pengumuman",
  "/wali-home-links":   "pengumuman",
  "/profil-pesantren":  "profil",
  "/devices":           "rfid",
  "/audit":             "audit",
  "/rfid-monitor":      "rfid",
  "/rfid-dashboard":    "rfid",
  "/rfid-transactions": "rfid",
  "/rfid-topup":        "rfid",
  "/rfid-merchant":     "rfid",
  "/rfid-devices":      "rfid",
  "/rfid-mutasi":       "rfid",
  "/rfid-refund":       "rfid",
  "/users":             "sistem",
  "/roles":             "sistem",
};
