export const ENDPOINTS = {
  LOGIN: '/wali-app/login',
  ME: '/wali-app/me',
  ANAK: '/wali-app/anak',
  DASHBOARD: '/wali-app/dashboard',
  FEATURES: '/wali-app/features',
  HOME_LINKS: '/wali-app/home-links',
  SANTRI_PROFIL: '/wali-app/santri/profil',
  SAHRIYAH: '/wali-app/sahriyah',
  SAHRIYAH_RIWAYAT: (id) => `/wali-app/sahriyah/${id}/riwayat`,
  RFID_SALDO: '/wali-app/rfid/saldo',
  RFID_MUTASI: '/wali-app/rfid/mutasi',
  ABSENSI: '/wali-app/absensi',
  PERIZINAN: '/wali-app/perizinan',
  PELANGGARAN: '/wali-app/pelanggaran',
  KESEHATAN: '/wali-app/kesehatan',
  NILAI: '/wali-app/nilai',
  HAFALAN: '/wali-app/hafalan',
  PENGUMUMAN: '/wali-app/pengumuman',
  NOTIFICATIONS: '/wali-app/notifications',
  NOTIFICATIONS_UNREAD_COUNT: '/wali-app/notifications/unread-count',
  NOTIFICATION_READ: (id) => `/wali-app/notifications/${id}/read`,
  NOTIFICATIONS_READ_ALL: '/wali-app/notifications/read-all',
  DEVICE_TOKEN: '/wali-app/device-token',
  DEVICE_TOKEN_STATUS: '/wali-app/device-token/status',
  PROFIL_PESANTREN: '/wali-app/profil-pesantren',
  CHANGE_PIN: '/wali-app/pin',
  PUSH_TOKEN: '/wali-app/push-token',
  TEST_NOTIFICATION: '/wali-app/test-notification',
};
